owner: seodani
repo: status

sites:
  # ==================================================
  # kr-central - 서버 자체
  # ==================================================

  - name: 다니엘 스튜디오 (kr-central)
    check: "tcp-ping"
    url: kr-central.danielstudio.kr
    port: 443

  # kr-central 하위 서비스

  - name: 다니엘 스튜디오 홈페이지
    url: https://danielstudio.kr

  - name: 다니엘 스튜디오 콘텐츠 서버
    url: https://contents.danielstudio.kr

  - name: 다니엘 스튜디오 요리 레시피
    url: https://cookrecipe.danielstudio.kr


  # ==================================================
  # kr-storage-01 - 서버 자체
  # ==================================================

  - name: 다니엘 스튜디오 (kr-storage-01)
    check: "tcp-ping"
    url: kr-storage-01.danielstudio.kr
    port: 443

  # kr-storage-01 하위 서비스

  - name: 다니엘 스튜디오 스토리지 서버
    url: https://kr-storage-01.danielstudio.kr


  # ==================================================
  # kr-edge-01 - 서버 자체
  # ==================================================

  - name: 다니엘 스튜디오 (kr-edge-01)
    check: "tcp-ping"
    url: kr-edge-01.danielstudio.kr
    port: 443

  # kr-edge-01 하위 서비스

  - name: 다니엘 스튜디오 새로운 콘텐츠 서버
    url: https://new-contents.danielstudio.kr


status-website:
  baseUrl: /status
  name: Daniel Studio Status
  introTitle: "다니엘 스튜디오 서비스 상태"
  introMessage: "다니엘 스튜디오에서 운영하는 서버 및 서비스의 현재 상태를 확인할 수 있습니다."
  theme: light

# 짧은 장애도 기록 보존
skipDeleteIssues: true

# 5분마다 검사
workflowSchedule:
  uptime: "*/5 * * * *"
